
-- Enable pgvector for embeddings
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- Store document chunks and their 768-dimensional embeddings
CREATE TABLE IF NOT EXISTS public.chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    source TEXT,
    page INTEGER,
    embedding extensions.vector(768)
);

-- Store conversation history
CREATE TABLE IF NOT EXISTS public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    role TEXT,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
